apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    name: todo-mongodb
spec:
  volumes:
  - name: todo-mongo-vol
    persistentVolumeClaim:
        claimName: todo-pvc
  containers:
  - name: mongodb-1
    image: mongo:4.0.13
    command:
    - mongod
    - "--bind_ip"
    - "0.0.0.0"
    # resources:
    #   limits:
    #     memory: "128Mi"
    #     cpu: "500m"
    ports:
    - containerPort: 27017
    volumeMounts:
    - name: todo-mongo-vol
      mountPath: /data/db
      
