apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-server-app-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-server-app
  template:
    metadata:
      labels:
        app: todo-server-app
    spec:
      containers:
      - name: todo-server-app-1
        image: todo-server-kubernetes-app:latest 
        resources:
          requests:
            memory: "64Mi"
            cpu: "256m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: server-side-configs
        - secretRef:
            name: server-side-secrets
